# Configurazione dei workflow per generazione contenuti
workflows:
  standard:
    name: "Articolo Standard"
    description: "Articolo di 800-1000 parole su un topic specifico"
    steps:
      - task: "ricerca"
        description: "Raccogliere informazioni sul topic"
        agent: "researcher"
      - task: "struttura"
        description: "Definire la struttura dell'articolo"
        agent: "architect"
      - task: "scrittura"
        description: "Scrivere il contenuto dell'articolo"
        agent: "writer"
      - task: "editing"
        description: "Revisione e ottimizzazione del contenuto"
        agent: "editor"
      - task: "quality_check"
        description: "Verifica della qualità del contenuto"
        agent: "reviewer"

  whitepaper:
    name: "White Paper"
    description: "White paper tecnico di 3000+ parole con contenuto approfondito"
    steps:
      - task: "ricerca_approfondita"
        description: "Ricerca approfondita sul topic"
        agent: "researcher"
      - task: "struttura_whitepaper"
        description: "Definire la struttura del white paper"
        agent: "architect" 
      - task: "executive_summary"
        description: "Scrivere la sintesi esecutiva"
        agent: "writer"
      - task: "sezioni_tecniche"
        description: "Sviluppare le sezioni tecniche"
        agent: "writer"
      - task: "casi_studio"
        description: "Aggiungere casi studio e esempi"
        agent: "writer"
      - task: "editing_avanzato"
        description: "Revisione approfondita e formattazione"
        agent: "editor"
      - task: "quality_check_completo"
        description: "Verifica completa della qualità"
        agent: "reviewer"