# Workflow configurations for content generation

workflows:
  standard:
    steps:
      - task: research_and_outline
        description: "Ricerca informazioni e creazione della struttura del contenuto"
      - task: draft_and_edit
        description: "Scrittura e ottimizzazione del contenuto"
      - task: review_and_finalize
        description: "Revisione finale e formattazione del contenuto"

  extended_article:
    steps:
      - task: research
        description: "Ricerca approfondita e analisi delle fonti"
      - task: outline
        description: "Strutturazione dettagliata dei contenuti"
      - task: draft
        description: "Scrittura del contenuto esteso"
      - task: expert_review
        description: "Revisione tecnica e verifica accuratezza"
      - task: edit
        description: "Editing e ottimizzazione del testo"
      - task: finalize
        description: "Finalizzazione e formattazione professionale"

  whitepaper:
    steps:
      - task: research
        description: "Ricerca approfondita e raccolta dati"
      - task: outline
        description: "Strutturazione dettagliata del whitepaper"
      - task: technical_draft
        description: "Scrittura contenuto tecnico"
      - task: expert_review
        description: "Revisione tecnica approfondita"
      - task: edit
        description: "Editing professionale"
      - task: design
        description: "Formattazione e design professionale"
      - task: finalize
        description: "Finalizzazione e controllo qualità"

  social_content:
    steps:
      - task: research
        description: "Analisi trend e target audience"
      - task: brainstorm
        description: "Ideazione contenuti social"
      - task: draft
        description: "Creazione copy e contenuti"
      - task: optimize
        description: "Ottimizzazione per piattaforme social"
      - task: finalize
        description: "Finalizzazione e scheduling"