# Workflow configurations for content generation

workflows:
  standard:
    steps:
      - task: research
        description: "Ricerca e raccolta informazioni sul tema"
      - task: outline
        description: "Creazione della struttura del contenuto"
      - task: draft
        description: "Scrittura della prima bozza"
      - task: review
        description: "Revisione e miglioramento del contenuto"
      - task: finalize
        description: "Finalizzazione e formattazione"

  extended_article:
    steps:
      - task: research
        description: "Ricerca approfondita e analisi delle fonti"
      - task: outline
        description: "Strutturazione dettagliata dei contenuti"
      - task: draft
        description: "Scrittura del contenuto esteso"
      - task: expert_review
        description: "Revisione tecnica e verifica accuratezza"
      - task: edit
        description: "Editing e ottimizzazione del testo"
      - task: finalize
        description: "Finalizzazione e formattazione professionale"

  whitepaper:
    steps:
      - task: research
        description: "Ricerca approfondita e raccolta dati"
      - task: outline
        description: "Strutturazione dettagliata del whitepaper"
      - task: technical_draft
        description: "Scrittura contenuto tecnico"
      - task: expert_review
        description: "Revisione tecnica approfondita"
      - task: edit
        description: "Editing professionale"
      - task: design
        description: "Formattazione e design professionale"
      - task: finalize
        description: "Finalizzazione e controllo qualità"

  social_content:
    steps:
      - task: research
        description: "Analisi trend e target audience"
      - task: brainstorm
        description: "Ideazione contenuti social"
      - task: draft
        description: "Creazione copy e contenuti"
      - task: optimize
        description: "Ottimizzazione per piattaforme social"
      - task: finalize
        description: "Finalizzazione e scheduling"