# Workflow configurations for content generation

workflows:
  standard:
    steps:
      - task: research_and_outline
        description: "Ricerca informazioni e creazione della struttura del contenuto"
      - task: draft_and_edit
        description: "Scrittura e ottimizzazione del contenuto"
      - task: review_and_finalize
        description: "Revisione finale e formattazione del contenuto"